### ISSUE TITLE
Feature request: Show release date of the module

### ISSUE THREAD

**Issue by attiks** [vijaycs85/dpsb#2]

**Comment by vijaycs85** [comment]
We could add release date of a version, but I wonder the best way to display it.

**Comment by attiks** [comment]
Maybe show it when you hover the release button?

**Comment by vijaycs85** [comment]
@attiks: How do you feel about it in https://github.com/vijaycs85/dpsb/pull/4 ?

**Comment by vijaycs85** [comment]
Thanks for the feedback on the PR @attiks. I merged it!
